name: Update README TOC

on:
  push:
    paths:
      - 'content/**'     
    branches:
      - master              

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or your preferred version

      - name: Install dependencies
        run: pip install nbformat

      - name: Run TOC update script
        run: python scripts/readme-organizer.py
