name: Update README TOC

on:
  push:
    paths:
      - 'content/**'
      - 'README.md'
    branches:
      - master

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install nbformat

      - name: Run TOC update script
        run: python scripts/readme-organizer.py

      - name: Commit and push README if changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "✅ No changes to README.md"
          else
            git commit -m "🔄 Update README TOC"
            git push https://x-access-token:${GH_PAT}@github.com/Andrei0016/ML-Problem-Archive.git HEAD:master
          fi
